name = "Kita"
description = "Kita is a clean, elegant and simple blog theme for Zola."
license = "MIT"
homepage = "https://github.com/daradege/kita-farsi"
min_version = "0.17.0"
demo = "https://daradege.ir/kitafarsi"

[author]
name = "daradege"
homepage = "https://st1020.com"

[original]
author = "nanxiaobei"
homepage = "https://lee.so/"
repo = "https://github.com/nanxiaobei/hugo-paper"