[[project]]
name = "کیتا فارسی"
desc = "کیتا فارسی یک قالب زیبا، ساده و روان برای زولا است."
tags = ["بلاگ", "زولا", "فارسی", "قالب", "زولا", "فارسی", "کیتا", "فارسی", "کیتا فارسی"]
links = [
    { name = "گیت‌هاب", url = "https://github.com/daradege/kita-farsi" }
]